export enum Subscriptions {
  PLAYER_ADDED = 'PLAYER_ADDED',
  PLAYER_UPDATED = 'PLAYER_UPDATED',
  ARROW_UPDATED = 'ARROW_UPDATED',
  ACTIONS_RESOLVED = 'ACTIONS_RESOLVED',
  RESOLVE_ACTIONS = 'RESOLVE_ACTIONS',
  ACTION_ADDED = 'ACTION_ADDED',
}
